// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7sVGjpwCdSlCGs01Q5vx3RS87Yuk4MV8',
    appId: '1:716628313066:web:d422a50191ac7376302893',
    messagingSenderId: '716628313066',
    projectId: 'flyer-23604',
    authDomain: 'flyer-23604.firebaseapp.com',
    storageBucket: 'flyer-23604.appspot.com',
    measurementId: 'G-SDJLDPVS33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIE3vO1XnZ3XVhfQjQh_ZofGvX1uNjBXg',
    appId: '1:716628313066:android:68c3a60c37b66698302893',
    messagingSenderId: '716628313066',
    projectId: 'flyer-23604',
    storageBucket: 'flyer-23604.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV_8a0KBMYLtDC8VK9XR-uy37yXMWbJrA',
    appId: '1:716628313066:ios:47b3c8eac5dd2330302893',
    messagingSenderId: '716628313066',
    projectId: 'flyer-23604',
    storageBucket: 'flyer-23604.appspot.com',
    androidClientId: '716628313066-c80cf5i9mb05ltsrgfr9q14f823e0a7d.apps.googleusercontent.com',
    iosClientId: '716628313066-hdstfiv04kdmkom4jiafnfb5m5pccmh0.apps.googleusercontent.com',
    iosBundleId: 'com.michaelblason.flyer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV_8a0KBMYLtDC8VK9XR-uy37yXMWbJrA',
    appId: '1:716628313066:ios:47b3c8eac5dd2330302893',
    messagingSenderId: '716628313066',
    projectId: 'flyer-23604',
    storageBucket: 'flyer-23604.appspot.com',
    androidClientId: '716628313066-c80cf5i9mb05ltsrgfr9q14f823e0a7d.apps.googleusercontent.com',
    iosClientId: '716628313066-hdstfiv04kdmkom4jiafnfb5m5pccmh0.apps.googleusercontent.com',
    iosBundleId: 'com.michaelblason.flyer',
  );
}
